<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>de.swa</groupId>
	<artifactId>gmaf-semantics-mvr</artifactId>
	<version>1.0.3-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>GMAF Semantics</name>
	<description></description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>14</maven.compiler.source>
		<maven.compiler.target>14</maven.compiler.target>
	</properties>
	<repositories>
		<repository>
			<id>github</id>
			<url>https://maven.pkg.github.com/marquies/gmaf-mvr</url>
		</repository>
	</repositories>
	<distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub marquies Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/marquies/gmaf-mvr</url>
		</repository>
	</distributionManagement>
	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>

		<!--		<dependency>-->
		<!--			<groupId>de.swa</groupId>-->
		<!--			<artifactId>gmaf-ext-plugins</artifactId>-->
		<!--			<version>1.0.0</version>-->
		<!--		</dependency>-->
		<dependency>
			<groupId>com.bordercloud</groupId>
			<artifactId>SPARQL-JAVA</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>de.swa</groupId>
			<artifactId>gmaf-mvr</artifactId>
			<version>1.0.5-SNAPSHOT</version>
		</dependency>
	</dependencies>

</project>
